Hw12 calendar
Serega2780/otus-golang-hw pull request #13
Opened 2024-08-31 07:51 UTC by Serega2780

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер, мидлвара удовлетворяет ТЗ - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

2024-08-31 08:07 UTC, vladislavmass requested changes

2024-08-31 08:07 UTC, vladislavmass commented on hw12_13_14_15_calendar/internal/storage/memory/storage_test.go
> +		for _, e := range storage.db {
Вот тут нет мьютекса.  И может одновременно идти и итерирование и удаление

2024-08-31 08:07 UTC, vladislavmass commented on hw12_13_14_15_calendar/internal/storage/memory/storage_test.go
> +	t.Run("find by id", func(t *testing.T) {
А что проверяет этот тест? Если куча потоков пишет в id причем одновременно

2024-08-31 08:11 UTC, Serega2780 commented on hw12_13_14_15_calendar/internal/storage/memory/storage_test.go
> +	t.Run("find by id", func(t *testing.T) {
вот тут так и подозревал.. Спасибо! Переделал на атомики

2024-08-31 08:11 UTC, Serega2780 commented on hw12_13_14_15_calendar/internal/storage/memory/storage_test.go
> +		for _, e := range storage.db {
да, таки осознал. Перекопировал в отдельнуюю мапу

2024-08-31 08:12 UTC, Serega2780 commented on hw12_13_14_15_calendar/internal/storage/memory/storage_test.go
> +	t.Run("find by id", func(t *testing.T) {
Да просто работа метода FindByID. Нужен был реальный возвращаемый Insert id-шник, так как они генерируются на этапе вставки

2024-09-02 18:10 UTC, vladislavmass approved these changes

2024-09-06 08:30 UTC, merged