HW2 is completed
Serega2780/otus-golang-hw pull request #2
Opened 2024-06-10 14:44 UTC by Serega2780

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-06-10 22:03 UTC, vladislavmass requested changes

2024-06-10 22:03 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	bcsl := false
Что такое bcsl? имя переменной не несет в себе никакой информации о его назначение

2024-06-10 22:03 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		str = str[:len(str)-1]
В го лучше не использовать обращение по индексу для строк. Так как такая операция адресует не символ а 1 байт символа. И если для однобайтовой кодировки это сработает, то для многобайтовых кодировок это не сработает. Для демонстрации проблемы можно использовать следующий тест кейс `{input: "aaф0b", expected: "aab"},`

2024-06-11 08:22 UTC, Serega2780 commented on hw02_unpack_string/unpack.go
> +	bcsl := false
Переименовал в backSlash - флаг, показывающий, что в строке уже обнаружен \

2024-06-11 08:23 UTC, Serega2780 commented on hw02_unpack_string/unpack.go
> +		str = str[:len(str)-1]
Переделал на удаление именно последней руны

2024-06-13 08:28 UTC, vladislavmass requested changes

2024-06-13 08:28 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	var sb strings.Builder
Раз уж мы используем strings.Builder в основном для передачи по ссылке, то было бы лучше сделать из sb сразу указатель на strings.Builder, чем каждый раз получать его адрес

2024-06-13 08:28 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		case v == 92:
Не очень понятно что такое 92. Лучше было бы сделать это константой с понятным именем

2024-06-13 10:13 UTC, Serega2780 commented on hw02_unpack_string/unpack.go
> +	var sb strings.Builder
добавил указатель

2024-06-13 10:13 UTC, Serega2780 commented on hw02_unpack_string/unpack.go
> +		case v == 92:
добавил константу

2024-06-13 11:29 UTC, vladislavmass approved these changes

2024-06-13 12:47 UTC, merged