HW4 is completed
Serega2780/otus-golang-hw pull request #4
Opened 2024-06-25 14:52 UTC by Serega2780

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-06-26 05:19 UTC, vladislavmass requested changes

2024-06-26 05:19 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		if lru.queue.Len() > lru.capacity {
Капасити это размер который не должен быть превышен даже на пару таков процессора.

2024-06-26 05:19 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	elements map[Key]*ListItem
Мапы тут быть не должно

2024-06-26 05:19 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	case Pair:
связный список ничего не должен знать о структурах которые в ней хранятся. Поэтому этого свитч быть не должно

2024-06-26 05:19 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		if l.front == nil {
l.front==nil произойдет только если в связном списке еще нет ни одного элемента. А при добавление 1 элемента он должен стать и первы и последним

2024-06-26 05:19 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		case l.front:
При удаление единственного элемента из списка будет паника

2024-06-26 05:28 UTC, Serega2780 commented on hw04_lru_cache/list.go
> +	elements map[Key]*ListItem
> Сложность всех операций должна быть O(1), т.е. не должно быть мест, где осуществляется полный обход списка.

если не будет мапы, как добиться удаления за О(1), и не пробежаться по-твоему списку?

2024-06-26 05:30 UTC, Serega2780 commented on hw04_lru_cache/list.go
> +	case Pair:
Как тогда передать ключ в мапу выше? Ну и тот же вопрос: как обойтись без неё и соблюсти О(1) для удаления?

2024-06-26 05:32 UTC, Serega2780 commented on hw04_lru_cache/list.go
> +		if l.front == nil {
А как проверить, что список пустой? Как раз i.front==nil. Нужно же определить, что доставляемый элемент первый

2024-06-26 05:33 UTC, Serega2780 commented on hw04_lru_cache/cache.go
> +		if lru.queue.Len() > lru.capacity {
Хотелось бы больше подробностей, что не так

2024-06-26 05:38 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		if lru.queue.Len() > lru.capacity {
Как работает текущая реализация.  Предположим что у нас уже в кэше 10 элементов.
В начале в кэш добавляется 11 элемент, чего быть не должно и только потом удаляется лишний.

А должно быть. Посмотрели что в кэшэ уже 10 элементов, удалили последний. Осталось 9. Добавили новый элемент

2024-06-26 05:41 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	elements map[Key]*ListItem
Тут идет попытка сделать подстроить связный список под кэш. Что не допустимо. Pair должен хранится в поле Value структуры ListItem

2024-06-26 05:42 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		if l.front == nil {
Проблема тут не в этом. Проблема в том, что когда мы добавили 1 элемент мы не сделали его еще и  последним

2024-06-26 05:50 UTC, Serega2780 commented on hw04_lru_cache/list.go
> +	elements map[Key]*ListItem
Нет. Тут я вставил мапу только из-за требования выполнять все операции (и удаление из списка) за О(1). Я ещё даже не читал требования к кэшу. Изначально у меня ключ был string и я его генерировал из value. Была идея генерить uuid, но решил, что перебор для учебной задачи. Key уже сделал потом для универсальности. В классическом списке нет возможности удалять за О(1). Т.е. без мапы там не обойтись. Ну, или есть какая-то неизвестная мне структура.

2024-06-26 05:55 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	elements map[Key]*ListItem
в условиях задания есть такая сноска `Считаем, что методы Remove и MoveToFront вызываются только от существующих в списке элементов.` поэтому проверка на наличие не нужна

2024-06-26 16:59 UTC, Serega2780 commented on hw04_lru_cache/cache.go
> +		if lru.queue.Len() > lru.capacity {
Поменял местами добавление нового и удаление самого старого при превышении размера кэша

2024-06-26 16:59 UTC, Serega2780 commented on hw04_lru_cache/list.go
> +	elements map[Key]*ListItem
убрал мапу

2024-06-26 16:59 UTC, Serega2780 commented on hw04_lru_cache/list.go
> +	case Pair:
убрал switch

2024-06-26 17:00 UTC, Serega2780 commented on hw04_lru_cache/list.go
> +		if l.front == nil {
back = front, если добавлен первый элемент

2024-06-26 17:00 UTC, Serega2780 commented on hw04_lru_cache/list.go
> +		case l.front:
учел

2024-06-27 08:57 UTC, vladislavmass approved these changes

2024-06-27 08:57 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		if temp.Next == nil {
Какой кейс обрабатывает данный код?

2024-06-27 09:03 UTC, Serega2780 commented on hw04_lru_cache/list.go
> +		if temp.Next == nil {
да, видимо лишнее... Раньше для одного элемента у меня front не был равен back. Тут из-за этого терялся хвост.

2024-06-27 09:05 UTC, merged