HW5 is completed
Serega2780/otus-golang-hw pull request #5
Opened 2024-07-01 14:34 UTC by Serega2780

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-07-02 13:44 UTC, vladislavmass requested changes

2024-07-02 13:44 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	errs := make(chan struct{}, len(tasks))
не очень хорошая идея делать канал с неизвестным размером буфера буфером. Лучшая идея это не буферезированый канал

2024-07-02 13:44 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	for _, t := range tasks {
Предположим мы отправили последнюю задачу и вышли из этого цикла. воркеры делают последние n задач и одна из них заканчивается с ошибкой. Будет ли эта ошибка учтена?

2024-07-03 12:29 UTC, Serega2780 commented on hw05_parallel_execution/run.go
> +	for _, t := range tasks {
Что-то вообще никаких идей. Как дождаться все сообщения errs, если в него пишут n горутин и ни одна из них не может закрыть канал, так как упадут остальные при попытке записи...

2024-07-03 12:30 UTC, Serega2780 commented on hw05_parallel_execution/run.go
> +	errs := make(chan struct{}, len(tasks))
с небуверизованным зависание странное. Вроде воркеры в него пишут, main читает, а все равно все висит

2024-07-03 14:18 UTC, Serega2780 commented on hw05_parallel_execution/run.go
> +	errs := make(chan struct{}, len(tasks))
поменял логику

2024-07-03 14:18 UTC, Serega2780 commented on hw05_parallel_execution/run.go
> +	for _, t := range tasks {
поменял логику

2024-07-03 18:04 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	errs := make(chan struct{}, len(tasks))
Вообще это ожидаемое поведение.
```
            case <-errs:
			errCount++
			if m > 0 && errCount >= m {
				close(tc)
				breakWithError = true
				break
			} else {
				tc <- t
			}
		default:
			tc <- t // если во всех активных горутинах проихошли ошибки, то они все лочаться на запись в канал ошибок и и считать из канала tc просто некому.
```

Правильной идеей было бы сделать так. 
```
             case <-errs:
			errCount++
			if m > 0 && errCount >= m {
				close(tc)
				breakWithError = true
				break
			}
		case tc <- t:
```

2024-07-03 18:07 UTC, vladislavmass approved these changes
Хорошая работа, но код переусложнен из-за лишних блоков if.

2024-07-03 18:07 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +func worker(wg *sync.WaitGroup, tc <-chan Task, errC *atomic.Uint64, m int, ignoreE bool) {
Зачем наделять воркер каким-то задачеспецифичным контекстом? Этот метод прекрасно бы работал и без ignoreE

2024-07-04 07:09 UTC, Serega2780 commented on hw05_parallel_execution/run.go
> +func worker(wg *sync.WaitGroup, tc <-chan Task, errC *atomic.Uint64, m int, ignoreE bool) {
Без  ignoreE на 57 строке цикл обработчика бы прервался и остались бы незавершенные задачи

2024-07-04 07:27 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +func worker(wg *sync.WaitGroup, tc <-chan Task, errC *atomic.Uint64, m int, ignoreE bool) {
Как я уже говорил ранее, варке не должен принимать решение когда ему закончить работу. Единственный момент когда он может закончить работу это или закрытие канала, или получиения сигнала о том, что ему нужно закончить работу. Но сам думать что у него слишком много ошибок и поэтому я закроюсь он не должен

2024-07-04 07:48 UTC, Serega2780 commented on hw05_parallel_execution/run.go
> +func worker(wg *sync.WaitGroup, tc <-chan Task, errC *atomic.Uint64, m int, ignoreE bool) {
понял. исправил

2024-07-04 07:51 UTC, merged