HW8 try 1
Serega2780/otus-golang-hw pull request #8
Opened 2024-07-31 10:46 UTC by Serega2780

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-07-31 12:31 UTC, vladislavmass requested changes

2024-07-31 12:31 UTC, hungry-honeybadger commented on hw08_envdir_tool/env_reader.go
> +		str := strings.TrimRight(string(envValue), WhiteSpace)
Пробелы мы убрали, но что на счет таблуяции

2024-07-31 12:31 UTC, hungry-honeybadger commented on hw08_envdir_tool/main.go
> +	RunCmd(os.Args[2:], env)
Код с которым завершился программу нужно вернуть, тут он просто теряется

2024-07-31 16:41 UTC, Serega2780 commented on hw08_envdir_tool/env_reader.go
> +		str := strings.TrimRight(string(envValue), WhiteSpace)
Убрал табуляцию

2024-07-31 16:41 UTC, Serega2780 commented on hw08_envdir_tool/main.go
> +	RunCmd(os.Args[2:], env)
Возвращаю код RunCmd()

2024-07-31 17:31 UTC, vladislavmass approved these changes

2024-07-31 17:31 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +			if buf[0] == 10 || errors.Is(fErr, io.EOF) {
Использование "магического" числа 10.

2024-07-31 17:31 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +		if fi.IsDir() {
Почему = в имени файла мы игнорим, а вот директория приводит к ошибке? В чем причина столь разного поведения ?

2024-08-01 06:44 UTC, Serega2780 commented on hw08_envdir_tool/env_reader.go
> +		if fi.IsDir() {
![image](https://github.com/user-attachments/assets/cae6895e-7108-48db-a568-37f775420cac)
В задании сказано, что имя файла не должно содержать =, но не сказано, как это обрабатывать, поэтому я просто пропуска. такой файл. Настоящая утилита envdir падает ровно с такой ошибкой, как сделал я, для случая, когда есть вложенная директория

2024-08-01 06:49 UTC, Serega2780 commented on hw08_envdir_tool/env_reader.go
> +			if buf[0] == 10 || errors.Is(fErr, io.EOF) {
Использую константу

2024-08-01 07:49 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +		if fi.IsDir() {
Однообразно обрабатывать ситуации было бы более правильным поведением

2024-08-01 08:02 UTC, merged